### ISSUE TITLE
F-Droid can't reproduce build

### ISSUE THREAD

**Issue by linsui** [upvpn/upvpn-app#14]
https://gitlab.com/fdroid/fdroiddata/-/jobs/5699086937

It's not reproducible.

[diff.zip](https://github.com/upvpn/upvpn-app/files/13596549/diff.zip)

Could you please take a look? Thanks!

**Comment by licaon-kter** [comment]
It looks like the upstream APK was built from some commit that's not in the tree, a lot of extra stuff

**Comment by 64bit** [comment]
Hello, thank you for the issue and info

I believe its because of the feedback in fdroiddata Merge Request that I should pin NDK version.  Which lead to different commit (for F-Droid) and tag (for Google Play) used for first app.

The tag (u1-beta-4) and commit [8d86362](https://github.com/upvpn/upvpn-app/commit/8d86362a1bb80a0f003105c42c00f2c10a9f5c93) are mentioned in release notes https://github.com/upvpn/upvpn-app/releases/tag/android-u1-beta-4

I believe this wont be an issue going forward with [u2](https://github.com/upvpn/upvpn-app/releases/tag/android-u2-5) release. Yes?

**Comment by linsui** [comment]
I'm not sure what you mean. u2 is the version not reproducible. We build it from the tag. Which commit should we use?

**Comment by 64bit** [comment]
Sorry for the confusion. There is no change in build files after first version. 

But to make sure (and double check based on @licaon-kter  comment) I have recreated self signed apk from tag `android-u2-5` 

https://github.com/upvpn/upvpn-app/releases/download/android-u2-5/UpVPN-u2-5-self-signed.apk 

Does this resolve the issue on your end?

**Comment by linsui** [comment]
Still the same problem...

**Comment by 64bit** [comment]
That's unfortunate. You guys understand F-Droid build system best - let me know what changes are required to make it work.

But since you guys build and sign it before publising on F-Droid - I'm ok to drop reproducibility if big unknown on how to achieve it.

**Comment by licaon-kter** [comment]
Comparing @linsui's build https://gitlab.com/linsui/fdroiddata/-/jobs/5722097112#L123 with your new one https://github.com/upvpn/upvpn-app/releases/tag/android-u2-5 the diff is still rather odd :(

[upvpn5.log](https://github.com/upvpn/upvpn-app/files/13635463/upvpn5.log)

**Comment by linsui** [comment]
Maybe it's caused by cache. And please make sure openjdk 17 is used. Then please clean the cache and rebuild the apk.

**Comment by licaon-kter** [comment]
That's repro :tada:

**Comment by linsui** [comment]
Thanks!

**Comment by 64bit** [comment]
Thank you all for following through, when to expect this version to be live?

**Comment by 64bit** [comment]
haha nice 😌

**Comment by 64bit** [comment]
Seems like website is oudated still, when to expect it to reflect description of u2 version?

**Comment by licaon-kter** [comment]
@64bit it's live https://f-droid.org/packages/app.upvpn.upvpn/

**Comment by 64bit** [comment]
Thank you for your response. 

Actually, the full description is old (and misleading to users). The current full description on website and in repo are different for quite some time now https://github.com/upvpn/upvpn-app/blob/main/metadata/en-US/full_description.txt 

Is there any build related issue for Website that needs to be addressed?

**Comment by licaon-kter** [comment]
It's this one, right?

https://github.com/upvpn/upvpn-app/blob/android-u2-5/metadata/en-US/full_description.txt

**Comment by licaon-kter** [comment]
Yes, well, the text needs to match the app, there's no point in having it say _"5 colors"_ but that version is not yet ready and the current one has only "2" :))

**Comment by 64bit** [comment]
That makes sense. I have created a new release to fix this (I have only updated versionCode) 

Here's the link: https://github.com/upvpn/upvpn-app/releases/download/android-u2-6/UpVPN-u2-6-self-signed.apk

**Comment by licaon-kter** [comment]
Yup, I've updated the recipe.  👍

**Comment by linsui** [comment]
It failed again. 
[upvpn.html.zip](https://github.com/upvpn/upvpn-app/files/14318449/upvpn.html.zip)

Could you please take a look? Thanks!

**Comment by 64bit** [comment]
That's really unfortunate. I have regenerate the APKs, does it resolve it now?

Also this doesnt seem sustainable - perhaps remove the reproducible build requirement? And rely on immutable tags on this repo

**Comment by linsui** [comment]
https://gitlab.com/linsui/fdroiddata/-/jobs/6198049478 It's not reproducible yet.

**Comment by 64bit** [comment]
What needs to change? 

Otherwise please drop reproducibility?

**Comment by 64bit** [comment]
@linsui @licaon-kter any tips on how to get resolve this?

**Comment by 64bit** [comment]
I did the same old drill - clear cache - open jdk 17. Rebuild the apk again and have updated file in Release notes

Hopefully that should resolve it? If that still doesnt work But I need to hear from you long term fix - to remove reproducibility requirement - its not serving any purpose for you or me does it?

**Comment by 64bit** [comment]
For follow up https://gitlab.com/fdroid/fdroiddata/-/issues/3194

**Comment by licaon-kter** [comment]
>  Rebuild the apk again and have updated file in Release notes

testing now

**Comment by 64bit** [comment]
Thanks, did it work?

**Comment by licaon-kter** [comment]
not sure what happened, I was sure I posted the log 3 days go, _(wonder **where** I posted it :fearful:)_

anyway, here it is, kinda the same as above: 
[upvpn7.log](https://github.com/upvpn/upvpn-app/files/14387242/upvpn7.log)
