### ISSUE TITLE
Add Themed/Monochrome Icon

### ISSUE THREAD

**Issue by NielSync** [upvpn/upvpn-app#15]
![Screenshot_20240202-114827~2.jpg](https://github.com/upvpn/upvpn-app/assets/20804647/dec37f98-e8cd-4e29-a0a9-2f0efa7baa70)

**Comment by 64bit** [comment]
Looks like spam

**Comment by 64bit** [comment]
Thank you for the comment. The original description looked like spam, after the edit it looks genuine, thank for creating a better description, reopening to resolve this.

**Comment by 64bit** [comment]
Thank you for the issue, latest Android app supports themed icons:

![Screenshot from 2024-10-28 15-00-34](https://github.com/user-attachments/assets/aac7ccbe-a681-4204-b1be-6557b3696423)
