### ISSUE TITLE
Feature request: protocol

### ISSUE THREAD

**Issue by Pantyhose-X** [upvpn/upvpn-app#16]
In regions such as China, Iran, North Korea, Ukraine, etc., it is difficult to connect to a VPN. 
It is recommended to add the following protocol.

[mieru Proxy Protocol](https://github.com/enfein/mieru)
[trojan Protocol](https://trojan-gfw.github.io/trojan/)
[geneva Protocol](https://github.com/Kkevsterrr/geneva)
[n2n Protocol](https://github.com/ntop/n2n)

**Comment by 64bit** [comment]
Thanks for the issue, only WireGuard is supported.
