### ISSUE TITLE
Support iOS

### ISSUE THREAD

**Issue by murka** [upvpn/upvpn-app#25]
What about supporting the iOS?

**Comment by 64bit** [comment]
Hi there, thank you for your interest in iOS app! 

Its a work in progress, please register here to get notified when it becomes available: https://upvpn.app/vpn-for-ios-ipados/

**Comment by 64bit** [comment]
iOS app is now available on the App Store: https://apps.apple.com/app/serverless-vpn-upvpn/id6596774170

And source code is available here: https://github.com/upvpn/upvpn-app/tree/main/upvpn-apple/UpVPN
